#!/bin/bash
# ============================================================================
#  AKAZA X PROXY  -  One-shot setup script
#  Run this on your Linux server (or Termux on Android).
#
#  What it does:
#    1. Creates a Python virtual environment (`.venv`)
#    2. Installs all dependencies from requirements.txt
#    3. Asks you for BOT_TOKEN and ADMIN_ID
#    4. Writes them to `.env` (so you don't have to edit code)
#    5. Starts the bot
#
#  Usage:
#      bash setup.sh
# ============================================================================
set -e

cd "$(dirname "$0")"

# Color codes (works in most terminals)
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'  # no color

echo ""
echo "=================================================="
echo -e "${CYAN}  AKAZA X PROXY  -  Setup Wizard${NC}"
echo "  v6.2 — Phone-friendly"
echo "  Credit: @akaza_isnt"
echo "=================================================="
echo ""

# --- Check Python ---
echo -e "${YELLOW}[1/5] Checking Python...${NC}"
if command -v python3 >/dev/null 2>&1; then
    PY=python3
elif command -v python >/dev/null 2>&1; then
    PY=python
else
    echo -e "${RED}❌ Python 3 is not installed.${NC}"
    echo ""
    echo "Install it first:"
    echo "  Ubuntu/Debian:  sudo apt install python3 python3-pip python3-venv"
    echo "  Termux:         pkg install python"
    echo "  Alpine:         apk add python3 py3-pip"
    exit 1
fi
echo -e "${GREEN}✅ Found: $($PY --version)${NC}"
echo ""

# --- Create virtual environment ---
echo -e "${YELLOW}[2/5] Creating virtual environment (.venv)...${NC}"
if [ -d ".venv" ]; then
    echo -e "${GREEN}✅ .venv already exists — skipping${NC}"
else
    $PY -m venv .venv
    echo -e "${GREEN}✅ Created .venv${NC}"
fi
echo ""

# --- Install dependencies ---
echo -e "${YELLOW}[3/5] Installing Python dependencies...${NC}"
.venv/bin/pip install --upgrade pip --quiet
.venv/bin/pip install -r requirements.txt --quiet
echo -e "${GREEN}✅ Dependencies installed${NC}"
echo ""

# --- Ask for credentials ---
echo -e "${YELLOW}[4/5] Configure your bot${NC}"
echo ""
echo "You need two things:"
echo "  • BOT_TOKEN  → from @BotFather on Telegram (looks like 123456:ABC-DEF...)"
echo "  • ADMIN_ID   → your numeric Telegram user ID (from @userinfobot)"
echo ""

# If .env already exists, show current values
if [ -f ".env" ]; then
    echo -e "${YELLOW}Existing .env found. Press Enter to keep current value.${NC}"
    CURRENT_TOKEN=$(grep "^BOT_TOKEN=" .env | cut -d= -f2-)
    CURRENT_ADMIN=$(grep "^ADMIN_ID=" .env | cut -d= -f2-)
fi

# Ask for BOT_TOKEN
if [ -n "$CURRENT_TOKEN" ] && [ "$CURRENT_TOKEN" != "BOT_TOKEN=" ]; then
    read -p "BOT_TOKEN [current: ${CURRENT_TOKEN:0:15}...]: " NEW_TOKEN
    TOKEN="${NEW_TOKEN:-$CURRENT_TOKEN}"
else
    read -p "BOT_TOKEN: " TOKEN
fi

if [ -z "$TOKEN" ]; then
    echo -e "${RED}❌ BOT_TOKEN is required.${NC}"
    exit 1
fi

# Ask for ADMIN_ID
if [ -n "$CURRENT_ADMIN" ]; then
    read -p "ADMIN_ID [current: $CURRENT_ADMIN]: " NEW_ADMIN
    ADMIN="${NEW_ADMIN:-$CURRENT_ADMIN}"
else
    read -p "ADMIN_ID: " ADMIN
fi

if [ -z "$ADMIN" ]; then
    echo -e "${RED}❌ ADMIN_ID is required.${NC}"
    exit 1
fi

# Write .env
cat > .env <<EOF
# AKAZA X PROXY — auto-generated by setup.sh
BOT_TOKEN=$TOKEN
ADMIN_ID=$ADMIN
EOF

echo -e "${GREEN}✅ Saved to .env${NC}"
echo ""

# --- Start the bot ---
echo -e "${YELLOW}[5/5] Starting the bot...${NC}"
echo ""
echo "=================================================="
echo -e "${GREEN}  Bot is starting! Open Telegram and send /start${NC}"
echo "=================================================="
echo ""
echo "To stop:        press Ctrl+C"
echo "To restart:     bash setup.sh    (then press Enter to keep values)"
echo "To run later:   .venv/bin/python AKAZA_X_PROXY_Bot.py"
echo ""
echo "--------------------------------------------------"
echo ""

exec .venv/bin/python AKAZA_X_PROXY_Bot.py
